imdb/parser/http/__init__.py, imdb/parser/http/personParser.py
This adds a new http parser that parse's the data from an actor's resume page. The resume can be accessed with the 'resume' key. Everything is taken in pretty raw format. Here is an example of a resume page http://www.imdb.com/name/nm5993268/resume?ref_=nm_ov_res
=> Added a new http parser to parse a Persons's resume page

.gitignore, imdb/parser/http/movieParser.py, tests/conftest.py, tests/test_http_movie_combined.py, tests/test_http_person_main.py
This fixes color info with notes parsing in the movie combined parser. It also fixes the test data for series seasons and adds some person tests. Now all initial tests for the movie combined parser pass for Python 3.3, 3.4, 3.5, 3.6, and pypy3, both with and without lxml.
=> Make all initial tests pass

tests/conftest.py, tests/test_http_chart_bottom.py, tests/test_http_chart_top.py, tests/test_http_movie_combined.py, tests/test_http_movie_keywords.py, tests/test_http_movie_plot.py, tests/test_http_movie_taglines.py, tests/test_http_movie_votes.py, tests/test_http_person_main.py, tests/test_http_search_character.py, tests/test_http_search_company.py, tests/test_http_search_movie.py, tests/test_http_search_person.py, tox.ini
This PR makes the tests use IMDbPY's URL opener instead of urllib.urlopen. This makes sure that the URL opener is tested and also makes it possible to test the parts which include cookie handling.
=> Use IMDbPY's URL opener in tests

imdb/parser/http/personParser.py
This PR fixes the following pieces in the HTML person bio parser: headshot, birth date, death date, nicknames. It still doesn't fix spouse, trade mark, trivia, and salary.
=> Fix some parts of the bio parser

imdb/parser/http/movieParser.py
As usual, the HTML detail changed.
Given we need this at work and we're not even around moving to Python 3 it would seem best to me to be able to fix things we find in `imdbpy-legacy` branch. Otherwise we'll need to fork this anyway.
=> Change from ol to ul when looking for official sites

imdb/parser/http/movieParser.py, tests/test_http_movie_combined.py
This PR fixes the following pieces of data in the movie combined details parser: genres, aspect ratio, plot outline, color info, sound mix, country and country codes, language and language codes, runtime. Note that the combined page lists only a single color and a single runtime for a movie now. And the MPAA rating is removed.
=> Fix movie parsing with failing tests

imdb/parser/http/__init__.py, imdb/parser/http/movieParser.py, tests/test_http_movie_combined.py
Requests for movie combined details pages now redirect to ".../reference" instead of "/combined". This PR changes the URLs to avoid unnecessary redirects.
=> change movie combined page URL to end with /reference

imdb/parser/http/movieParser.py
This PR fixes the parsers for Directors and Writers for the new version of the site.
```
>>> from imdb import IMDb
>>> ia = IMDb()
>>> the_matrix = ia.get_movie('0133093')
>>> print(the_matrix['director'])
[<Person id:0905154[http] name:_Wachowski, Lana_>, <Person id:0905152[http] name:_Wachowski, Lilly_>]
>>> print(the_matrix['writer'])
[<Person id:0905152[http] name:_Wachowski, Lilly_>, <Person id:0905154[http] name:_Wachowski, Lana_>]
```
=> fix writers and directors parsers (part of #103)

.gitignore, imdb/parser/http/movieParser.py, imdb/parser/http/utils.py
Previous regexp didn't match TV series (and probably other kinds).
Sample `og_tilte` values
```
Agents of S.H.I.E.L.D. (TV Series 2013– )
Lost (TV 2004–2010)
The Matrix (1999)
```
Related to #103 
Before
```
In [7]: ia.get_movie('2364582')
Out[7]: <Movie id:2364582[http] title:_None_>
```
After
```
In [3]: ia.get_movie('2364582')
Out[3]: <Movie id:2364582[http] title:_"Agents of S.H.I.E.L.D." (2013)_>
```
Parsed title
```
In [6]: analyze_og_title(u'Agents of S.H.I.E.L.D. (TV Series 2013– )')
Out[6]: 
{'kind': u'tv series',
'series years': u'',
'title': u'Agents of S.H.I.E.L.D.',
'year': 2013}
In [7]: analyze_og_title(u'Lost (TV Series 2004–2010)')
Out[7]: {'kind': u'tv series', 'series years': u'2010', 'title': u'Lost', 'year': 2004}
In [8]: analyze_og_title(u'The Matrix (1999)')
Out[8]: …
```
=> Fix og_title matching - empty dict for kinds other than movie

imdb/parser/http/topBottomParser.py, tests/test_http_chart_top.py
This is a minor fix for getting rank values in top/bottom chart parsers. It also adds tests for checking some entry contents.
=> Fix rank parsing in top/bottom parsers

imdb/parser/http/movieParser.py
Some tv shows don't have year in the `og:title` metadata field. This is a quick fix that handles those cases. Only downside is that the dict returned from `analyze_og_title` doesn't contain `year` nor `series years` so probably some tests will break? Not sure where those values are used.
Example of such tv show:  `'3336458': 'viva la madness'`
=> Fix title parsing for tv shows without a year

docs/README.package, docs/imdbpy.cfg, imdb/Company.py, imdb/Movie.py, imdb/__init__.py, imdb/_logging.py, imdb/helpers.py, imdb/parser/http/__init__.py, imdb/parser/http/characterParser.py, imdb/parser/http/companyParser.py, imdb/parser/http/movieParser.py, imdb/parser/http/personParser.py, imdb/parser/http/searchCharacterParser.py, imdb/parser/http/searchCompanyParser.py, imdb/parser/http/searchKeywordParser.py, imdb/parser/http/searchMovieParser.py, imdb/parser/http/searchPersonParser.py, imdb/parser/http/topBottomParser.py, imdb/parser/http/utils.py, imdb/utils.py
I've backported IMDb redesign patches from #103 to legacy branch.
1. Identify beginning of the patches
2. Used `git rev-list --reverse <commit_id>..master -- imdb/parser/http | git cherry-pick --stdin`
3. In first commit I saw very large conflicts
4. Searched for PEP8 related commits
5. Cherry-picked PEP8 related commits
6. Redone the second step
7. When looking at conflicts, I've taken extra care at `u` prefixes and `str/unicode` functions
8. Any special change I have documented in commit message
Hope this helps to anyone. But since, the legacy branch does not have any tests, this patch is likely going to be a cowboy ride on production :).
I've also decided to cherry-pick every commit as-is for easier review (if I've missed something solving the conflicts).
=> Imdbpy legacy redesign backport

imdb/parser/http/movieParser.py
This fixes `KeyError: u'notes'` exception because many release dates don't have notes. Now `notes` are accessed the same way as `country` and `date` so the `if notes` statement makes more sense (in addition to checking falsy values).
=> Fix movieParser post processing of release dates - KeyError: %s if notes key is missing

imdb/parser/http/movieParser.py
Example [releaseinfo](https://www.imdb.com/title/tt1677720/releaseinfo#akas)
As you can see, country is (now?) in `td[1]` and title in `td[2]`.
Akas are returned with swapped title and country values now, e.g.:
```
{u'countries': u'Avengers: Infinity War', u'title': u'Mexico'},
{u'countries': u'Avengers: Wojna bez granic', u'title': u'Poland'},
{u'countries': u'Vingadores: Guerra do Infinito', u'title': u'Portugal'},
```
This PR fixes this behaviour.
=> Fix release info akas - swap title with countries

imdb/parser/http/movieParser.py
As discussed in https://github.com/alberanid/imdbpy/issues/159#issuecomment-404282108, this PR adds two new keys with `akas` in `release dates` in more machine-friendly formats (lists of dicts).
I'm not sure if this is the best place but _it works_.
```
In [7]: movie.get('raw release dates')                                                                                  
Out[7]:                                                                                                                 
[{u'country': u'USA',                                                                                                   
u'date': u'13 February 2018',                                                                                         
u'notes': u' (Westwood, California)\n (premiere)'}, …
```
=> Retain raw akas and raw release dates after parsing release info

imdb/locale/rebuildmo.py
Sort input file list
so that mo files are created in a reproducible way
in spite of indeterministic filesystem readdir order
and http://bugs.python.org/issue30461
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on reproducible builds for openSUSE.
=> Sort input file list

imdb/utils.py, tests/test_http_search_movie.py
Issue #168 
Add the information of season and episode when parsing TV episodes in movie search
```python
>>> from imdb import IMDb
>>> ia = IMDb()
>>> movies = ia.search_movie('Architect of Destruction')
>>> for m in movies:
...     if m['kind'] == 'episode':
...         print(m['episode of'], m['season'], m['episode'])
... 
How I Met Your Mother 6 5
```
Added a test.
=> add season and episode in analyze_title for TV series episodes #168

imdb/parser/http/movieParser.py, tests/test_http_movie_full_credit.py
Fixed a but in my headshot PR. Most of the headshots were coming up with default no picture option  because IMDB is smart about lazy loading images. Pulling from `loadlate` attribute instead of `src` fixes the issue.
=> pull headshot from loadlate instead of src

imdb/utils.py
Fixed the failing python2 tests. I think the tests I created for my last pr `test_http_movie_full_credit.py` exposed a bug in the python2 code for getting full credits. I checked locally on 2.7 with a commit before my headshot PR and the tests fail in the same way.
To fix it I copied the same check for when an actor has multiple roles (line 1227). Though I admit, I didn't look too hard as to why a `currentRole` gets set to a unicode object on python2 and thus cannot have the `characterID` attribute set.
=> fix role for python2

imdb/__init__.py, imdb/parser/http/__init__.py, tests/test_http_search_keyword.py
The function `get_keyword` is great, since it lets you find movies by a keyword.  However, it doesn't currently support pagination, and it also triggers a page redirect since the URL is the old one.
Let's switch this to use the new URL format `/search/keyword/?keywords=superhero&page=12`, and add a test to make sure this works as expected.
=> Enable pagination of search-for-movie-by-keyword

imdb/parser/http/__init__.py, imdb/parser/http/movieParser.py
Hello!
For my current research, I need something similar to recommendations for movies. 
As IMDb does not provide "recommendations" section itself now I used "More Like This" section (see https://help.imdb.com/article/imdb/discover-watch/what-is-the-more-like-this-section/GPE7SPGZREKKY7YN?ref_=cons_tt_rec_lm#).
So, I used your library and also add recommendations parser from "More Like This" from the main movie page.
Use in the following way:
```
>>> from imdb import IMDb
>>> ia = IMDb()
>>> ia.get_movie_recommendations("0133093")
['1375666', '0120737', '0167261', '0167260', '0137523', '0109830', '0110912', '0120815', '0102926', '0120689', '0080684', '0114369']
```
=> feat: movie recommendations parser

imdb/__init__.py, imdb/parser/http/__init__.py
Changes made:
1. Modified get_movie_episodes method to allow for parsing/fetching of a subset of the series seasons.
2. Created the update_series_seasons method. This is the exposed method that handles only episode retrieval requests for specific seasons.
Resolves #245
=> Add selective season parsing for series

imdb/locale/msgfmt.py, imdb/parser/http/utils.py, tests/test_http_movie_sites.py
Fixes an exception when getting refs fails, which calls a logger warning that has the wrong number or arguments.
=> Fix not format string with incorrect number of substitutions

imdb/parser/http/searchMovieAdvancedParser.py
- The updated regex satisfies imdbIndex in group 10: https://regex101.com/r/k90bfx/2
- Reran steps to reproduce #267 , and error no longer occurs - search_movie_advanced successfully returned a list of parsed movie objects.
=> Update _re_secondary_info regex to support imdbIndex without a year

imdb/parser/http/piculet.py
Different logger name was used. `__name__` magic var starts from `imdb`, but root logger is named `imdbpy`. As a result changes to `imdbpy` logger didn't had any effect on piculet, like `using lxml html builder` output.
I was not sure if full module name should be used or package instead. Decided to use package.
At some point, this and other loggers maybe should be refactored and use `getChild` on root logger instead of explicitly providing full names.
=> fix: use imdbpy root logger

imdb/parser/s3/__init__.py
Trivial fix for #278 .
The wrong table was used as the base of the select statement
=> Fix s3 parser get_movie_main to use title_episode table as needed

imdb/__init__.py, imdb/_exceptions.py, imdb/parser/http/__init__.py, imdb/parser/http/logging.py, imdb/parser/http/piculet.py, imdb/parser/http/utils.py, imdb/parser/logging.py, imdb/parser/sql/__init__.py, imdb/parser/sql/alchemyadapter.py, imdb/parser/sql/dbschema.py, imdb/parser/sql/logging.py, imdb/utils.py
Related to #274 
Instead of getting a named logger using the core logging package in every module, which is susceptible for typos, it now uses derived loggers by calling the `getChild` method on parent logger instances. This way we only provide the logger suffix, not the whole name.
@alberanid Maybe all `aux`-suffixed loggers should be deprecated in favour of package root loggers? For example instead of using `imdbpy.parser.http.aux`, the `imdbpy.parser.http` (that's now defined as `imdb.parser.http.logging.logger`) is enough?
=> Use derived loggers

tests/test_http_person_bio.py
Either Julia Roberts changed her height or her agent did.
Test was failing due to this change, so this commit brings it into parity with what's currently displayed on imdb.
=> fix test based on julia roberts's height

imdb/locale/msgfmt.py
array.tostring() was deprecated in Python 3.2 and removed in 3.9.
=> msgfmt.py: use array.tobytes() on Python >= 3.2

imdb/parser/http/__init__.py, tests/test_http_movie_season_episodes.py
Closes #300 
`season_nums` parameter of `IMDbHTTPAccessSystem.get_movie_episodes` and `IMDbHTTPAccessSystem.update_series_seasons` can now accept any sequence or iterable type.
Python `set` type is used internally for lists, tuples or any other object that does not implement `in` operator, otherwise the object's own `in` (`__contains__`) implementation is used. Single `int` parameters (not in a list) are also supported, as before.
I've added some tests. The test runner does not work on my system but running the tests manually works.
=> Change get_movie_episodes season_nums to accept any sequence or iterable

imdb/parser/http/movieParser.py
in reference to https://github.com/alberanid/imdbpy/issues/251
Changed *original title* to get actual original title, where available. Added *localized title* to keep the title which was previously under "original title".
Both are (now) stripped of the year, which original title wasn't before. I subbed in localized title because it can differ from "title", even if there is no "original title".
for me, but ymmv: https://www.imdb.com/title/tt2991224/ and https://www.imdb.com/title/tt2991224/reference show respectively tangerines (title) and mandariinid (now localized title).
=> updated original title

imdb/utils.py
Search-results for mini-series reported their "kind" as a movie, instead of the correct result. IMDb apparently spells it as "TV Mini Series" now, but that's not what IMDbPY was looking for.
=> Fix "kind" for mini-series in search-results #331

imdb/parser/http/__init__.py
In the current implementation imdbpy will crash with a citical error if a season is not found.
Reason: Imdbpy assumes a season listed does also exist in the episode list. Sometimes that is not the case, especially when a show only lists episodes by year. This data quality issue depends on each specific tv show, (e.g. "tt0388629": One Piece 1999) - but should never lead to a critical error. 
With "tt0388629" for some reason one season is listed on IMDb, but that season will return a 404, thus the two additional try/catches.
=> Prevent critical error #330

imdb/parser/http/movieParser.py, imdb/utils.py
In IMDB, there is a movie kind (TV Specials) that is not provided by IMDB in meta tag, So we have to get it from somewhere else despite of other kinds, I added this feature.
=> Feature: Adding TV Special support in movie kinds

imdb/helpers.py
Some images were not evaluated correctly, because of double @ symbol, or its absence.
Samples:
Original
resizeImage(Original, 300, 300)
Status on load
MV5BMjExMDQ4MDc4Ml5BMl5BanBnXkFtZTgwMTMwNzE4MDE@._V1_UY100_CR39,0,100,100_AL_.jpg	MV5BMjExMDQ4MDc4Ml5BMl5BanBnXkFtZTgwMTMwNzE4MDE@._V1_SX300_SY300_.jpg
OK
MV5BMTQ4ODU3NDM1Nl5BMl5BanBnXkFtZTgwMTA4NjE4MDE@._V1_UY100_CR39,0,100,100_AL_.jpg
MV5BMTQ4ODU3NDM1Nl5BMl5BanBnXkFtZTgwMTA4NjE4MDE@._V1_SX300_SY300_.jpg
OK
MV5BMjI2NDQ3NDQ1Nl5BMl5BanBnXkFtZTcwOTA3NDc1NA@@._V1_UY100_CR25,0,100,100_AL_.jpg
MV5BMjI2NDQ3NDQ1Nl5BMl5BanBnXkFtZTcwOTA3NDc1NA@._V1_SX300_SY300_.jpg
Not found
MV5BMjAyNzIzNTQ0MV5BMl5BanBnXkFtZTcwMTE3NDc1NA@@._V1_UY100_CR25,0,100,100_AL_.jpg
MV5BMjAyNzIzNTQ0MV5BMl5BanBnXkFtZTcwMTE3NDc1NA@._V1_SX300_SY300_.jpg
Not found …
=> Better treatment for @ character in resizeImage()

imdb/helpers.py
Today I found a bug related to the id. 
Previously, the length of the id was equal to 7 characters, now there is a variant with 7 and 8 characters.
Example: id with 8 characters in url - https://www.imdb.com/title/tt10872600/
=> fix regular expression for ID from url

imdb/parser/http/movieParser.py, tests/test_http_movie_combined.py
This is useful and incurs no overhead to have link of imdb trailers for movie. (Although it is just the video's page not the video direct link which is not available in imdb)
=> adding 'videos' key to extract movie trailer links

imdb/parser/http/movieParser.py, tests/test_http_movie_parental_guide.py
The new key is named "advisory votes" and a sample value of that is like this:
{'nudity': {'votes': {'None': 0, 'Mild': 6, 'Moderate': 3, 'Severe': 1}, 'status': 'Mild'},
'violence': {'votes': {'None': 0, 'Mild': 1, 'Moderate': 1, 'Severe': 0}, 'status': 'Moderate'},
'profanity': {'votes': {'None': 0, 'Mild': 1, 'Moderate': 0, 'Severe': 0}, 'status': 'Mild'},
'alcohol': {'votes': {'None': 1, 'Mild': 0, 'Moderate': 0, 'Severe': 0}, 'status': 'None'}}
=> adding parental guide advisory votes

imdb/helpers.py
Using the imdb.helpers.resizeImage
In some cases the movie poster/cover url is empty. There is no poster or something else happened to the url.
The resizeImage() fails to find the url with the default regex.
Also allow to provide custom regex for urls.
=> Raise exception on resize image

imdb/utils.py
Remove any extra quotes in title.
This is a fix for [issue 395](https://github.com/cinemagoer/cinemagoer/issues/395)
=> Fix for issue 395 "'Hangar 10' breaks movie search"

imdb/parser/http/__init__.py
IMDb no longer seems to accept an empty User-Agent for some requests and returns an HTTP-error 405. This patch sets a User-Agent of "alberanid/Cinemagoer", which so far IMDb appears to accept.
Signed-off-by: Nita Vesa <werecatf@outlook.com>
=> IMDbURLopener: set User-Agent in retrieve_unicode() #415

imdb/__init__.py
Fix for issue #426.
IMDb has changed the url path for searching for titles from: 
```
https://www.imdb.com/find?q=the+batman&s=tt (308 redirect)
https://www.imdb.com/find/?q=the+batman&s=tt (200) 
```
=> Fixed HTTPError 308: Permanent Redirect

imdb/parser/http/__init__.py, imdb/parser/http/personParser.py, tests/test_http_person_main.py
A possible fix for #424. 
Potential issues:
* `filmography` is not retrieved with `main` anymore. It could be mitigated by changing this new logic to something like `"full_filmography"` but I'm not sure what makes the most sense. 
* The `notes` portion of the film rules is not yet migrated (wasn't sure of a good example)
* I was guessing on a lot of this stuff. Very open to suggestions.
=> Parse Full Credits Page (Fix #424)

imdb/parser/http/movieParser.py
The `plotsummary` has been changed and the previous selector didn't work. The author field has been deleted from the page apparently.
=> Fix plot field in plotsummary page

imdb/parser/http/movieParser.py
Updated DOMHTMLTriviaParser in movieParser.py for trivia parsing. Only pulls the first 5 that are shown by default as rest are kept behind a 'More' button.
Fixes #467  
Example:
```
from imdb import Cinemagoer
ia = Cinemagoer()
movie = ia.get_movie('8589698', info=['trivia'])
movie['trivia']
```
Results:
```
['Ice Cube agreed to play Superfly because he liked the name and because he and his son watched TMNT cartoons.',
"Shredder was originally in the film, but was written out because writer Jeff Rowe wanted the film's villain to be a mutant that shared empathy with the Turtles and who could easily tempt/corrupt them.",
'In contrast to the norm for animation, the cast recorded their voice roles together in groups rather than independently from one another. A single recording session could …
```
=> #467 - Fixes DOMHTMLTriviaParser in movieParser.py

imdb/parser/http/movieParser.py
Cast can be listed in any order (alphabetic, for instance) and a "star" list can be useful. Moreover, this info is already available in the webpage retrieved by the "main" infoset.
=> Extract StarList

imdb/parser/http/movieParser.py
The metascore could also be parsed on the main page. I tried that but when you ask for `'main', 'critic reviews'` you get an error because of the duplicate key. I didn't want to remove the parsing of the metascore from 'critic reviews' in case a user does not also request the main data.
=> #439: fix parsing of critics reviews page

imdb/parser/http/movieParser.py
Built on top of a previous [PR 503](https://github.com/cinemagoer/cinemagoer/pull/503)
This PR includes the latest commits from main and an additional XPath fix. 
I was able to get the series code from the [docs](https://cinemagoer.readthedocs.io/en/latest/usage/series.html#series) to work as expected
```py
series = ia.get_movie('0389564')
ia.update(series, "episodes")
assert len(series["episodes"]) > 0
assert series["number of episodes"] > 0
```
=> XPath fixes for season episodes parser

imdb/parser/http/searchMovieParser.py
IMDb now seems to add multiple CSS classes to the corresponding class attributes, switched from `@class="X"` to `contains(@class, "X")` to address this
=> fix: corrected year and kind detection

imdb/parser/http/movieParser.py
DOM parser now selects the correct link.
Doesn't look to fix #526 
Here is a before and after
```python
from imdb import Cinemagoer as IMDb
ia = IMDb()
ia.get_movie(8416378).keys()
ia.get_movie(35673156).keys()
```
With fix applied:
```python
from imdb import Cinemagoer as IMDb
ia = IMDb()
ia.get_movie(8416378).keys()
ia.get_movie(35673156).keys()
```
The first episode example now correctly populated `episode of` and other attributes. Allowing a TV episode to go up to the parent show again.
=> Fix: Episode Parser - Show movieID
