imdb/Character.py, imdb/Company.py, imdb/Movie.py, imdb/Person.py, imdb/__init__.py, imdb/_exceptions.py, imdb/_logging.py, imdb/helpers.py, imdb/linguistics.py, imdb/locale/generatepot.py, imdb/locale/rebuildmo.py, imdb/parser/__init__.py, imdb/parser/http/__init__.py, imdb/parser/http/characterParser.py, imdb/parser/http/companyParser.py, imdb/parser/http/movieParser.py, imdb/parser/http/personParser.py, imdb/parser/http/searchCharacterParser.py, imdb/parser/http/searchCompanyParser.py, imdb/parser/http/searchKeywordParser.py, imdb/parser/http/searchMovieParser.py, imdb/parser/http/searchPersonParser.py, imdb/parser/http/topBottomParser.py, imdb/parser/http/utils.py, imdb/parser/sql/__init__.py, imdb/parser/sql/dbschema.py, imdb/utils.py, setup.cfg
These changes make the most modules nearly PEP-8 compliant. I will try to fix the remaining issues soon. I hope the style I've used is OK with you.
=> Codename simplify

.gitignore, setup.cfg, setup.py, tests/conftest.py, tests/test_http_movie_combined.py, tox.ini
Feel free to reject this if you decide not to incorporate these tests.
=> Add test infrastructure and some HTTP movie parser tests

tests/conftest.py, tests/test_http_chart_bottom.py, tests/test_http_chart_top.py, tests/test_http_movie_combined.py, tests/test_http_movie_keywords.py, tests/test_http_movie_plot.py, tests/test_http_movie_taglines.py, tests/test_http_person_main.py, tests/test_http_search_character.py, tests/test_http_search_company.py, tests/test_http_search_movie.py, tests/test_http_search_person.py
Improve the test infrastructure, add boilerplate code and initial tests for several page parsers.
=> Improve test setup

.gitignore, Makefile, setup.py
This changeset adds pytest-cov to the environment and a Makefile for simplifying build operations.
=> Add test coverage to build options

imdb/helpers.py, imdb/parser/http/__init__.py, imdb/parser/http/utils.py, imdb/utils.py, setup.cfg
These changes remove some unused code and do some minor style improvements.
=> Minor cleanup

imdb/parser/http/__init__.py
These also seem unnecessary now but I separated this pull request because I couldn't decide whether they could be needed somehow.
=> Remove the oldParsers and fallBackToNew parameters

imdb/parser/http/__init__.py, imdb/parser/http/movieParser.py, imdb/parser/http/utils.py
This PR adds an extractor for user reviews of a given title.
=> Parse user reviews

imdb/parser/http/personParser.py, tests/test_http_person_otherworks.py
This  PR fixes the person other works parser and adds tests for it.
=> Fix other works parser

setup.cfg, tests/conftest.py, tests/test_http_character_main.py, tests/test_http_company_main.py, tests/test_http_person_bio.py, tests/test_http_search_keyword.py, tests/test_http_search_movie.py, tests/test_http_search_movie_keyword.py
This PR adds tests for several http parsers.
=> Improve test suite

tests/test_http_character_main.py, tests/test_http_search_character.py
This PR disables the tests for character pages and character search pages since characters are title specific now.
=> Skip character page tests

imdb/parser/http/companyParser.py
This PR fixes the extraction of the company name data.
=> Fix company parser

imdb/parser/http/movieParser.py, imdb/parser/http/utils.py, imdb/utils.py, tests/test_http_movie_combined.py
This PR fixes the title, year and kind handling according to the new markup in the movie combined details page.
=> Fixes to movie titles, years and kinds

imdb/parser/http/movieParser.py, setup.py, tests/conftest.py, tests/test_http_movie_combined.py, tests/test_http_movie_reviews.py
This PR fixes the parsers and/or the tests that fail in the test suite. Now all tests in the test suite pass.
=> Fix failing movie parser tests

imdb/parser/http/companyParser.py, imdb/parser/http/movieParser.py, imdb/parser/http/personParser.py, imdb/parser/http/piculet.py, imdb/parser/http/searchCompanyParser.py, imdb/parser/http/searchKeywordParser.py, imdb/parser/http/searchMovieParser.py, imdb/parser/http/searchPersonParser.py, imdb/parser/http/topBottomParser.py, imdb/parser/http/utils.py, tests/test_http_gather_refs.py, tests/test_http_movie_combined.py, tests/test_http_movie_reviews.py, tests/test_http_movie_sites.py, tests/test_http_person_bio.py, tox.ini
This PR migrates all parsers to piculet rules and removes the existing extractor/attribute framework.
=> Piculet based parsers

imdb/parser/http/utils.py, tests/test_http_movie_combined.py, tests/test_http_movie_plot.py
Fix these four warnings... https://github.com/cclauss/imdbpy/pull/new/fix-warnings
=> Fix three of the four warnings at the end of py.test run

imdb/parser/http/searchMovieParser.py, imdb/parser/http/searchPersonParser.py, tests/test_http_search_movie.py, tests/test_http_search_person.py
I've modified the searchMovieParser to grab the poser URL in addition to the id/info/akas. I've also added in a test for this functionality. I've tested locally under python 3.7.
LMK if there is anything else needed as far as testing/documentation go.
=> grab poster from search

imdb/parser/http/movieParser.py, imdb/parser/http/utils.py, tests/test_http_movie_full_credit.py
Hi again!
This PR adds headshots to Person objects build when requesting "full credits" from movies. This was slightly simpler that my last PR, since the parent extractor was the role. I've also added a new test file to test the full credits selector, along with the new headshot feature. Happy to make changes if you want anything else to be done differently.
=> Extract actor headshot from full credits

imdb/__init__.py, imdb/parser/http/__init__.py, imdb/parser/http/searchMovieAdvancedParser.py, tests/test_http_search_movie_advanced.py
This PR adds a parser for the detailed title search page. It supports IMDb's sort criteria and also supports including adult titles. Adding more search criteria should be straightforward. Usage examples can be seen in the tests at the moment, the feature should be documented.
=> Advanced search

imdb/parser/http/movieParser.py
I found out that the imdbpy can not fetch awards information of the movie. I rewrote the DOMHTMLAwardsParser. So it can fetch the awards information
=> fixed the awards bugs in MovieParser.py

tests/test_http_person_bio.py
I saw that the build was failing and this was the reason. I also realized that it's not first time that Julia Roberts' height has been changed so it might be a good idea to test this with some other person :)
=> update testsuite: Julia Roberts suddenly got lower

imdb/parser/http/personParser.py
Person and movie parser was using the same/common parser. Now they are separated.
=> New "person awards" parser was implemented #234

imdb/helpers.py
https://github.com/alberanid/imdbpy/issues/265
=> helpers.resizeImage

bin/get_movie_list.py, imdb/__init__.py, imdb/parser/http/__init__.py, imdb/parser/http/listParser.py, tests/test_http_movie_list.py
I was missing the way to pull in lists, so this is what I came up with.
Mostly I tried to look at what was already in place and extend it to suit my needs.
Should I place my own name in the top of `listParser.py `, I wasn't sure about this.
=> Add imdb list as a source

docs/goodies/download_applydiffs.py, imdb/helpers.py, imdb/parser/http/companyParser.py, imdb/parser/http/movieParser.py, imdb/parser/http/personParser.py, imdb/parser/http/piculet.py, imdb/utils.py
=> Fix deprecation warnings due to invalid escape sequences.

imdb/locale/imdbpy-sr.po
=> Translated to serbian

bin/get_movie_list.py, imdb/parser/http/__init__.py
This was missing in the #273 and it just kept bothering me so I wrote an automatic pagination loop for lists.
I've tested with: ls027328830 it takes forever but it does work.
=> add pagination to get_movie_list

imdb/locale/msgfmt.py, setup.py
Resolves #310 
See [my four comments](https://github.com/alberanid/imdbpy/issues/310#issuecomment-821969092) for explanation.
=> Fix wheel build about locale files, fix .mo builds

imdb/parser/http/movieParser.py
Update review parsing to match what IMDB seems to do currently.
```
from imdb import IMDb
from pprint import pprint
ia = IMDb()
mov = ia.get_movie('11823076', ['reviews'])
pprint(mov['reviews'][1])
```
```
{'author': 'ur47521143',
'content': 'Bunch of low lifes keeping big cats. Unbelievable but very '
'entertaining.',
'date': '28 March 2020',
'helpful': 381,
'not_helpful': 92,
'rating': 8,
'title': 'Only in America'}
```
https://www.imdb.com/title/tt11823076/reviews
=> Handle review rating, title, helpful counts.

imdb/__init__.py, imdb/parser/http/__init__.py, imdb/parser/http/topBottomParser.py
Added methods to get top box office movies and to get top 50 movies by genres
=> Solve to issue #324: Top list search

imdb/__init__.py, imdb/parser/http/__init__.py, imdb/parser/http/showtimesParser.py, tests/test_get_showtimes.py
Add a feature that allows users to obtain showtimes for movies at cinemas near them with this page https://www.imdb.com/showtimes/.
Fixes issue https://github.com/cinemagoer/cinemagoer/issues/232.
=> Add showtimes feature.

imdb/parser/http/searchMovieParser.py
This appears to be span not label now.
=> Update search movies rules

imdb/utils.py
workaround for bug #350
this stops the empty person being output which in turn causes parseXML to fail
=> workaround for #350

imdb/utils.py
Fixed `SyntaxWarning: "is" with a literal.` Error
=> Fixed Syntax Error.

imdb/parser/http/personParser.py
Fixes #469 
Much like my previous pr #437, I'm not entirely sure what I'm doing, or if its the proper "style", but its at least towards a correct answer. I do more in the post-processor than individual transformers. 
It could be extended for the other fields listed in #462, but I'm leaving that for another day.
=> Date parsing fix

imdb/parser/http/movieParser.py
=> fix rating and cover url
